//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://example", ConfigurationName="ServiceReference1.sendmail")]
    public interface sendmail {
        
        // CODEGEN: Generating message contract since the operation sendEmail is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WindowsFormsApplication1.ServiceReference1.sendEmailResponse sendEmail(WindowsFormsApplication1.ServiceReference1.sendEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.sendEmailResponse> sendEmailAsync(WindowsFormsApplication1.ServiceReference1.sendEmailRequest request);
        
        // CODEGEN: Generating message contract since the operation sendEmailBatch is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WindowsFormsApplication1.ServiceReference1.sendEmailBatchResponse sendEmailBatch(WindowsFormsApplication1.ServiceReference1.sendEmailBatchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.sendEmailBatchResponse> sendEmailBatchAsync(WindowsFormsApplication1.ServiceReference1.sendEmailBatchRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://example", Order=0)]
        public string m_url;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://example", Order=1)]
        public string m_payload;
        
        public sendEmailRequest() {
        }
        
        public sendEmailRequest(string m_url, string m_payload) {
            this.m_url = m_url;
            this.m_payload = m_payload;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://example", Order=0)]
        public string sendEmailReturn;
        
        public sendEmailResponse() {
        }
        
        public sendEmailResponse(string sendEmailReturn) {
            this.sendEmailReturn = sendEmailReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendEmailBatchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://example", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public string[] url;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://example", Order=1)]
        public string payload;
        
        public sendEmailBatchRequest() {
        }
        
        public sendEmailBatchRequest(string[] url, string payload) {
            this.url = url;
            this.payload = payload;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendEmailBatchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://example", Order=0)]
        public string sendEmailBatchReturn;
        
        public sendEmailBatchResponse() {
        }
        
        public sendEmailBatchResponse(string sendEmailBatchReturn) {
            this.sendEmailBatchReturn = sendEmailBatchReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface sendmailChannel : WindowsFormsApplication1.ServiceReference1.sendmail, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class sendmailClient : System.ServiceModel.ClientBase<WindowsFormsApplication1.ServiceReference1.sendmail>, WindowsFormsApplication1.ServiceReference1.sendmail {
        
        public sendmailClient() {
        }
        
        public sendmailClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public sendmailClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public sendmailClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public sendmailClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.ServiceReference1.sendEmailResponse WindowsFormsApplication1.ServiceReference1.sendmail.sendEmail(WindowsFormsApplication1.ServiceReference1.sendEmailRequest request) {
            return base.Channel.sendEmail(request);
        }
        
        public string sendEmail(string m_url, string m_payload) {
            WindowsFormsApplication1.ServiceReference1.sendEmailRequest inValue = new WindowsFormsApplication1.ServiceReference1.sendEmailRequest();
            inValue.m_url = m_url;
            inValue.m_payload = m_payload;
            WindowsFormsApplication1.ServiceReference1.sendEmailResponse retVal = ((WindowsFormsApplication1.ServiceReference1.sendmail)(this)).sendEmail(inValue);
            return retVal.sendEmailReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.sendEmailResponse> WindowsFormsApplication1.ServiceReference1.sendmail.sendEmailAsync(WindowsFormsApplication1.ServiceReference1.sendEmailRequest request) {
            return base.Channel.sendEmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.sendEmailResponse> sendEmailAsync(string m_url, string m_payload) {
            WindowsFormsApplication1.ServiceReference1.sendEmailRequest inValue = new WindowsFormsApplication1.ServiceReference1.sendEmailRequest();
            inValue.m_url = m_url;
            inValue.m_payload = m_payload;
            return ((WindowsFormsApplication1.ServiceReference1.sendmail)(this)).sendEmailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.ServiceReference1.sendEmailBatchResponse WindowsFormsApplication1.ServiceReference1.sendmail.sendEmailBatch(WindowsFormsApplication1.ServiceReference1.sendEmailBatchRequest request) {
            return base.Channel.sendEmailBatch(request);
        }
        
        public string sendEmailBatch(string[] url, string payload) {
            WindowsFormsApplication1.ServiceReference1.sendEmailBatchRequest inValue = new WindowsFormsApplication1.ServiceReference1.sendEmailBatchRequest();
            inValue.url = url;
            inValue.payload = payload;
            WindowsFormsApplication1.ServiceReference1.sendEmailBatchResponse retVal = ((WindowsFormsApplication1.ServiceReference1.sendmail)(this)).sendEmailBatch(inValue);
            return retVal.sendEmailBatchReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.sendEmailBatchResponse> WindowsFormsApplication1.ServiceReference1.sendmail.sendEmailBatchAsync(WindowsFormsApplication1.ServiceReference1.sendEmailBatchRequest request) {
            return base.Channel.sendEmailBatchAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.sendEmailBatchResponse> sendEmailBatchAsync(string[] url, string payload) {
            WindowsFormsApplication1.ServiceReference1.sendEmailBatchRequest inValue = new WindowsFormsApplication1.ServiceReference1.sendEmailBatchRequest();
            inValue.url = url;
            inValue.payload = payload;
            return ((WindowsFormsApplication1.ServiceReference1.sendmail)(this)).sendEmailBatchAsync(inValue);
        }
    }
}
